

class Companies:
    companies = {
        "AAPL": "Apple Inc.",
        "MSFT": "Microsoft Corporation",
        "AMZN": "Amazon.com Inc.",
        "GOOGL": "Alphabet Inc. (Google's parent company)",
        "FB": "Meta Platforms Inc. (formerly Facebook Inc.)",
        "TSLA": "Tesla Inc.",
        "BRK.B": "Berkshire Hathaway Inc.",
        "V": "Visa Inc.",
        "JNJ": "Johnson & Johnson",
        "WMT": "Walmart Inc.",
        "BABA": "Alibaba Group Holding Limited",
        "NVDA": "NVIDIA Corporation",
        "JPM": "JPMorgan Chase & Co.",
        "UNH": "UnitedHealth Group Incorporated",
        "HD": "The Home Depot, Inc.",
        "PG": "Procter & Gamble Co.",
        "DIS": "The Walt Disney Company",
        "MA": "Mastercard Incorporated",
        "NFLX": "Netflix Inc.",
        "XOM": "Exxon Mobil Corporation",
        "IBM": "International Business Machines Corporation",
        "PYPL": "PayPal Holdings Inc.",
        "BMW.DE": "Bayerische Motoren Werke AG (BMW)",
        "INTC": "Intel Corporation",
        "CSCO": "Cisco Systems, Inc.",
        "PFE": "Pfizer Inc.",
        "KO": "The Coca-Cola Company",
        "PEP": "PepsiCo, Inc.",
        "BA": "Boeing Company",
        "ORCL": "Oracle Corporation",
        "ABBV": "AbbVie Inc.",
        "MRK": "Merck & Co., Inc.",
        "VZ": "Verizon Communications Inc.",
        "COST": "Costco Wholesale Corporation",
        "NKE": "NIKE, Inc.",
        "LLY": "Eli Lilly and Company",
        "MCD": "McDonald's Corporation",
        "GILD": "Gilead Sciences, Inc.",
        "F": "Ford Motor Company",
        "CVX": "Chevron Corporation",
        "BAC": "Bank of America Corp",
        "WFC": "Wells Fargo & Company",
        "C": "Citigroup Inc.",
        "SCHW": "Charles Schwab Corporation",
        "GS": "The Goldman Sachs Group, Inc.",
        "MS": "Morgan Stanley",
        "BLK": "BlackRock, Inc.",
        "AMGN": "Amgen Inc.",
        "MO": "Altria Group, Inc.",
        "PM": "Philip Morris International Inc."
    }
    def get_companies(self, companies):
        return companies
